### ISSUE TITLE
Patch editing recipe functionality

### ISSUE THREAD

**Issue by euvinkeel** [cse110-fa21-group31/cse110-fa21-group31#140]
while writing cypress tests i found these bugs:

- Removing steps doesn't work in creating a new recipe (but add/remove for ingredients works, and adding steps works)
- When creating another new recipe _immediately after saving the last added recipe,_ the old info still lingers from the first created recipe in the form inputs; also, double the ingredients are added/deleted and double the steps are added (deleting steps still won't work here) (probably more event listeners being connected every time a new recipe is made)

**Comment by Skarlys** [comment]
solved!
