### ISSUE TITLE
[Bug] route appends after migrating from hash to /

### ISSUE THREAD

**Issue by XiiinSheng** [cse110-fa21-group31/cse110-fa21-group31#149]
Every time user navigates to a new page, the route is appended to the url instead of replacing everything on it, causing path reference issues and potential routing issue.

**Comment by XiiinSheng** [comment]
Because of this bug, the browser back button is not working anymore for more than 2 navigations. 
Multiple update>back>update>back also appends url multiple times.

**Comment by eric-filishtiner** [comment]
Updated due to multispa resync
