### ISSUE TITLE
[Bug] Duplicated navigation calls (event listener)

### ISSUE THREAD

**Issue by XiiinSheng** [cse110-fa21-group31/cse110-fa21-group31#159]
In the user flow of `recipeDetail => edit button to editRecipe => browser back button to recipeDetail => edit button to editRecipe`, after some iterations the navigate() will be called multiple times when going to editRecipe page. This also happens sometimes when going from `createRecipe => submit button to recipeDetail` user flow.

**Comment by celiaxiao** [comment]
This is a problem for every button we're doing addEventlistener. Javascript does remove previous 'click' eventlistener when we call addEventlistener(). So we're actually `appending` eventlistener again and again for the same button. To clear the previous eventlistener, we do
```javascript
var el = document.getElementById('el-id'),
    elClone = el.cloneNode(true);

el.parentNode.replaceChild(elClone, el);
```
to every button
