### ISSUE TITLE
Look up for db query about ingredent lists and tags

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#16]

**Comment by BjornLJohnson** [comment]
Are database queries based on the contents of arrays efficient? It would be useful to store tags and ingredients as arrays of arbitrary strings on our recipe entries, but we aren't sure what kind of implications this might have on speed of recipe retrieval. I'll do some research to make sure this is a reasonable thing to do and put some info on my findings here

**Comment by celiaxiao** [comment]
Easy to query based on the array/content about the object. The database has optimization dedicated to such kinds of queries. No need to worry about speed
