### ISSUE TITLE
Upload and store image

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#17]
how to let user upload and store images

**Comment by XiiinSheng** [comment]
**Storing directly in database** works well for small amount&size of images, as it's better for CRUD, easier for development, and has better consistency/integrity/durability/backup. But as the file size goes up, database will cost more in space and decrease in performance.  
**Storing images in file system and storing urls in database** requires more time and work towards building up the structure and connection to avoid inconsistency, but it has better performance for a large number of images. 3rd party providers work well (Amazon S3, etc.), but we might not be allowed to use them.   

In our case, we might not have enough time to build up complete structure and connection of file system, and we won't be in a real-life scenario where users upload a huge amount of files, so it may be okay to **store images directly in database**.  

Mongodb offers two specifications for storing images: 
* [**BSON**](https://docs.mongodb.com/manual/reference/bson-types/) is binary data types for data up to 16MB. (double, string, object, ...)
* [**GridFS**](https://docs.mongodb.com/manual/core/gridfs/) is a specification for storing larger files.  
  Essentially two new collections under a database `fs`, explicitly for files. Can probably save the ids in `recipe` collection and query in `fs` using that id.
