### ISSUE TITLE
Look into local storage with MongoDB

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#20]

**Comment by celiaxiao** [comment]
Add a demo about CRUD with MongoDB based on local storage

**Comment by kianezaz** [comment]
repo for demo: https://github.com/kianezaz/local-MongoDB-demo

**Comment by celiaxiao** [comment]
Research about using local storage to store user-generated data on browser

**Comment by kianezaz** [comment]
repo for local storage demo: https://github.com/kianezaz/local-storage-demo
