### ISSUE TITLE
Research and create demo for Google login API

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#30]

**Comment by XiiinSheng** [comment]
I finished a demo and will show it during Friday's meeting. Basically following steps in the reference tutorial. Repo attached below for reference. 

Reference: https://developers.google.com/identity/sign-in/web/sign-in
Demo: https://github.com/XiiinSheng/Google-login-demo/tree/master

According to TA, we don't need to focus on user login/signup feature, so we can just use google login only, and no need to edit any profile picture or name or password.

**Comment by XiiinSheng** [comment]
Next step: figure out how to let any users with .edu email to access

**Comment by XiiinSheng** [comment]
Google verifies projects configured for a user type of External and a publishing status of In production if they meet one or more of the OAuth verification criteria:

* You want to display an icon or display name for your project on the OAuth consent screen.
* Your project's OAuth clients request authorization of any sensitive or restricted scopes.
* The number of authorized domains for your project exceeds the domain count limit.
* There are changes to your project's OAuth consent screen configuration after a previous published, verified configuration. 

In our case, we don't meet these criteria so we don't need verification. As long as we set the scope to `external` and `in production` anyone with Google account can access our webapp.
