### ISSUE TITLE
Integrate disqus into the RecipeDetail page

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#88]
1. Create a demo for how to add Disqus (HTML element) to our recipe detail page
2. Make sure we have different Disqus connected data sources (separate list of comments) for different recipes
3. Figure out how to store these Disqus comments in our database, eg: store the name of Disqus connected database name
4. Finally take off the authorization inside Disqus itself, and prompt users to log in when they're not

**Comment by celiaxiao** [comment]
Update: integrate Disqus to recipeDetail page already. Having trouble to link different comments threads for different recipes. The `this.page.identifier` doesn't work. 

May need to change another tech if we can't figure it our by Wed.

**Comment by XiiinSheng** [comment]
Now Disqus is dynamically rendered. Next step is to sync Disqus login and the website login. See issue #165 for details.
